### ISSUE TITLE
Can't differentiate Tree Gnome Stronghold/Village

### ISSUE THREAD

**Issue by JelloRanger** [Hablapatabla/ImplingFinder#8]
Noticed a dragon imp spawn and its location was cut off in the side panel showing "Tree Gnome...". But it could be either the stronghold or the village according to this: https://github.com/Hablapatabla/ImplingFinder/blob/master/src/main/java/com/hablapatabla/implingfinder/model/ImplingFinderRegion.java#L69-L70

Ideally the location shouldn't be cut off or have a way to hover over to see the full name of the location, but a quick fix could be to just change "Tree Gnome Stronghold" to just "Gnome Stronghold" like how it's listed in the spirit tree teleportation menu in-game.

**Comment by Hablapatabla** [comment]
thanks. made the change. for anyone who may read this, clicking the specific impling should bring up a marker in your world map so there is no ambiguity.

**Comment by JelloRanger** [comment]
Ah I didn't know that was a thing! I think I tried double clicking to see if anything would happen but I probably didn't notice the flicker when I was doing that with the world map open. In any case though, thanks for the quick fix!
